#!/bin/bash
sudo wget https://github.com/odoope/Instalador-Odoo-Peru/blob/10.0/1604_v10_odoo_installation
sudo bash 1604_v10_odoo_installation
sudo wget https://raw.githubusercontent.com/odoope/Instalador-Odoo-Peru/10.0/odoo_nginx.sh
sudo bash odoo_peru_nginx
